const markup = "<div class=\"legal-page\">\n    <header class=\"site-nav\">\n      <a class=\"brand\" href=\"/\" aria-label=\"Rocky home\">\n        <img src=\"/pets/golem_male/idle.gif\" alt=\"\">\n        <span>Rocky</span>\n      </a>\n      <nav aria-label=\"Main navigation\">\n        <a href=\"/#pets\">Pets</a>\n        <a href=\"/#life\">Daily rhythm</a>\n        <a href=\"/#capabilities\">Capabilities</a>\n        <a href=\"/privacy\">Privacy</a>\n      </nav>\n      <a class=\"nav-cta\" href=\"/#download\">Download</a>\n    </header>\n\n    <main class=\"legal-main\">\n      <section class=\"legal-hero support-hero\">\n        <p class=\"section-kicker\">Support</p>\n        <h1>Need help with Rocky?</h1>\n        <p>Downloads, sign-in, install issues, updates, and app behavior.</p>\n      </section>\n\n      <section class=\"support-grid\">\n        <article class=\"legal-card support-card\">\n          <h2>Contact Support</h2>\n          <p>\n            Email us with your device, Windows version, Rocky version, and a short description of what happened.\n          </p>\n          <a class=\"button primary\" href=\"mailto:support@getrockyapp.com?subject=Rocky%20Support%20Request\">Email support</a>\n        </article>\n\n        <article class=\"legal-card support-card\">\n          <h2>Download Help</h2>\n          <p>\n            If the download does not start after Google sign-in, make sure popups are allowed for getrockyapp.com and try the download button again.\n          </p>\n          <a class=\"button glass\" href=\"/#download\">Back to download</a>\n        </article>\n      </section>\n\n      <article class=\"legal-card\">\n        <h2>Common Fixes</h2>\n        <h3>Google sign-in keeps asking again</h3>\n        <p>\n          Make sure cookies and popups are allowed for getrockyapp.com. If you are using a private browser window, try a normal browser window.\n        </p>\n\n        <h3>Windows blocks the installer</h3>\n        <p>\n          Windows may warn about new apps. Confirm you downloaded Rocky from getrockyapp.com and follow the Windows prompt only if you trust the file.\n        </p>\n\n        <h3>The app does not open after install</h3>\n        <p>\n          Restart Rocky from the Start menu. If it still does not open, email support with your Windows version and Rocky version.\n        </p>\n\n        <h3>I want to report a bug or request a feature</h3>\n        <p>\n          Email <a href=\"mailto:support@getrockyapp.com\">support@getrockyapp.com</a> with steps to reproduce, screenshots if useful, and what you expected Rocky to do.\n        </p>\n      </article>\n    </main>\n\n    <footer>\n      <span>Rocky Desktop Pet</span>\n      <span class=\"footer-links\">\n        <a href=\"/privacy\">Privacy</a>\n        <a href=\"/terms\">Terms</a>\n        <a href=\"/support\">Support</a>\n      </span>\n    </footer>\n  </div>";

export default function Page() {
  return (
    <>
      <div dangerouslySetInnerHTML={{ __html: markup }} />
    </>
  );
}

